CHOICES = {
            'alerts': [
                ("1", "Needs Watering"), 
                ("2", "Needs Pruning"), 
                ("3", "Should be Removed"), 
                ("4", "Pest Or Disease Present"), 
                ("5", "Guard Should Be Removed"), 
                ("6", "Stakes And Ties Should Be Removed"), 
                ("7", "Construction Work In The Area"), 
                ("8", "Touching Wires"), 
                ("9", "Blocking Signs or Traffic Signals"), 
                ("10", "Improperly Pruned or Topped"),
            ],
            'pests': [
                ("0", "None reported"),
                ("1", "Emerald Ash Borer"),
                ("2", "Hemlock Woolly Adelgid"),
                ("3", "Norway Maple Tar Spot"),
            ],
            'actions': [
                ("1", "Watered"), 
                ("2", "Pruned"), 
                ("3", "Removed"), 
                ("4", "Treated"), 
                ("5", "Guard Removed"), 
                ("6", "Stakes And Ties Removed"), 
            ],
            'projects': [
                ("1", "Montpelier Landmark"),
                ("2", "Historic Tree"),
                ("3", "Ash Borer Watch"),
                ("4", "Adelgid Watch"),
            ],
            'sidewalks': [
                ("1", "Minor or No Damage"),
                ("2", "Raised More Than 3/4 Inch"),
            ],
            'powerlines': [
                ("0", "PL N/A"),
                ("1", "None"),
                ("2", "Mild"),
                ("3", "Moderate"),
                ("4", "Severe"),
                ("5", "Fix ASAP"),
            ],
            'conditions': [
                ("0", "Cond N/A"),
                ("1", "Dead"),
                ("2", "Poor"),
                ("3", "Fair"),
                ("4", "Good"),
                ("5", "Excellent"),
            ],
            'canopy_conditions': [
                ("0", "Trim N/A"),
                ("1", "Contact"),
                ("2", "Branch"),
                ("3", "Leader"),
                ("4", "Tree Falling"),
            ],
            'plot_types': [
                ("0", "Type N/A"),
                ("1", "Sidewalk"),
                ("2", "< 4 ft"),
                ("3", "> 4 ft"),
                ("4", "Lawn"),
            ],
            'plot_stewardship': [
                ("1","Watering"),
                ("2","Pruning"),
                ("3","Mulching, Adding Compost or Amending Soil"),
                ("4","Removing Debris or Trash"),
            ],
            'tree_stewardship': [
                ("1","Enlarging the Planting Area"),
                ("2","Adding a Guard"),
                ("3","Removing a Guard"),
                ("4","Herbaceous Planting"),
            ]
    }
